version: '3.8'
services:
 API:
  container_name: unsolo_rockets
  image: unsolo-rockets
  ports:
   - "8080:8080"
  depends_on:
   - unsolo_rockets_db
  environment:
   - SPRING_PROFILES.DEFAULT=docker

 unsolo_rockets_db:
  container_name: unsolo_rockets_db
  image: postgres:13.3-alpine
  ports:
   - "5432:5432"
  environment:
   - SPRING_DATASOURCE_USERNAME=postgres
   - SPRING_DATASOURCE_PASSWORD=password
   - POSTGRES_DB=unsolo_rockets
   - POSTGRES_HOST_AUTH_METHOD=trust





