version: '3.8'
services:
 API:
  image: unsolo-rockets
  ports:
   - "8080:8080"
  depends_on:
   - db
  environment:
   - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/unsolo_rockets
   - SPRING_DATASOURCE_USERNAME=postgres
   - SPRING_DATASOURCE_PASSWORD=qwertyuiop
   - SPRING_JPA_HIBERNATE_DDL_AUTO=update

 db:
  image: postgres:13.3-alpine
  ports:
   - "5432:5432"

  environment:
   - SPRING_DATASOURCE_USERNAME=postgres
   - SPRING_DATASOURCE_PASSWORD=qwertyuiop
   - POSTGRES_DB=unsolo_rockets
   - POSTGRES_HOST_AUTH_METHOD=trust





